import mongoose from "mongoose";
import { randomUUID } from "node:crypto";

import * as parentRepository from "../repositories/parentRepository.js";
import * as activeLearningItemRepository from "../repositories/activeLearningItemRepository.js";
import * as learningAttemptRepository from "../repositories/learningAttemptRepository.js";

const RESUME_WINDOW_MS = 24 * 60 * 60 * 1000;
const CLAIM_LEASE_MS = 30 * 1000;
const DUPLICATE_KEY_ERROR_CODE = 11000;

class LearningItemError extends Error {
  constructor(reason) {
    super(`Learning item request rejected: ${reason}`);
    this.name = "LearningItemError";
    this.reason = reason; // "child_unavailable" | "not_found" | "conflict"
  }
}

function isDuplicateKey(error) {
  return error.code === DUPLICATE_KEY_ERROR_CODE;
}

function isWithinResumeWindow(snapshot, now) {
  return now.getTime() - snapshot.lastActivityAt.getTime() <= RESUME_WINDOW_MS;
}

async function runInTransaction(work) {
  const session = await mongoose.startSession();

  try {
    await session.withTransaction(() => work(session));
  } finally {
    await session.endSession();
  }
}

async function assertChildIsActive({ parentId, childId }, { session } = {}) {
  if (!(await parentRepository.findActiveChild(parentId, childId, { session }))) {
    throw new LearningItemError("child_unavailable");
  }
}

// The terminal record is built from the server's own snapshot, never from the caller.
function buildAttemptFromSnapshot(snapshot, { status, supportLevel, interactiveOutcome, expressiveState, endedAt }) {
  return {
    attemptId: snapshot.attemptId,
    parentId: snapshot.parentId,
    childId: snapshot.childId,
    missionId: snapshot.missionId,
    band: snapshot.band,
    contentFingerprint: snapshot.contentFingerprint,
    variationSignature: snapshot.variationSignature,
    status,
    supportLevel,
    interactiveOutcome,
    expressiveState,
    startedAt: snapshot.startedAt,
    endedAt,
  };
}

// Ending the item in the same transaction that deletes its snapshot is what
// keeps a stale item from being both interrupted and still resumable.
async function interruptIdleItem(snapshot, now) {
  const { parentId, childId, attemptId } = snapshot;
  const cutoff = new Date(now.getTime() - RESUME_WINDOW_MS);

  await runInTransaction(async (session) => {
    const deleted = await activeLearningItemRepository.deleteIdleSince(
      { parentId, childId, attemptId, cutoff },
      { session },
    );

    if (deleted) {
      await learningAttemptRepository.create(
        buildAttemptFromSnapshot(deleted, {
          status: "interrupted",
          supportLevel: deleted.supportLevel,
          interactiveOutcome: deleted.interactiveOutcome,
          expressiveState: deleted.expressiveState,
          endedAt: now,
        }),
        { session },
      );
    }
  });
}

// The child check and the snapshot insert share one transaction, and the child
// write conflicts with a concurrent archive, so no snapshot outlives an archive.
async function createSnapshotForActiveChild({ parentId, childId, ...itemFields }, now) {
  let snapshot;

  await runInTransaction(async (session) => {
    if (!(await parentRepository.recordChildSession(parentId, childId, now, { session }))) {
      throw new LearningItemError("child_unavailable");
    }

    snapshot = await activeLearningItemRepository.create(
      { parentId, childId, ...itemFields, attemptId: randomUUID(), startedAt: now, lastActivityAt: now },
      { session },
    );
  });

  return snapshot;
}

async function resumeConcurrentWinner(scope, originalError) {
  const winner = await activeLearningItemRepository.findForChild(scope);

  if (!winner) {
    throw originalError;
  }

  return { resumed: true, snapshot: winner };
}

// Resumes the child's unfinished item, or stores a new one. The item is
// generated by the caller; this module only owns its lifecycle.
async function startItem({ parentId, childId, now = new Date(), ...itemFields }) {
  const scope = { parentId, childId };

  await assertChildIsActive(scope);

  const existing = await activeLearningItemRepository.findForChild(scope);

  if (existing && isWithinResumeWindow(existing, now)) {
    const resumed = await activeLearningItemRepository.recordActivity({ ...scope, attemptId: existing.attemptId, now });

    if (resumed) {
      return { resumed: true, snapshot: resumed };
    }
  } else if (existing) {
    await interruptIdleItem(existing, now);
  }

  try {
    return { resumed: false, snapshot: await createSnapshotForActiveChild({ ...scope, ...itemFields }, now) };
  } catch (error) {
    if (!isDuplicateKey(error)) {
      throw error;
    }

    return resumeConcurrentWinner(scope, error);
  }
}

async function claimItem({ parentId, childId, attemptId, now = new Date() }) {
  const scope = { parentId, childId };

  if (!(await parentRepository.findActiveChild(parentId, childId))) {
    return { ok: false, reason: "not_found" };
  }

  const snapshot = await activeLearningItemRepository.tryClaim({ ...scope, attemptId, now, leaseMs: CLAIM_LEASE_MS });

  if (snapshot) {
    return { ok: true, snapshot };
  }

  const exists = await activeLearningItemRepository.findByAttemptId({ ...scope, attemptId });

  return { ok: false, reason: exists ? "conflict" : "not_found" };
}

async function releaseItem({ parentId, childId, attemptId, claimToken }) {
  await activeLearningItemRepository.release({ parentId, childId, attemptId, claimToken });
}

// Returns null when the caller's claim no longer holds, which is how a replay
// or a request that outlived its lease shows up.
async function endClaimedItem({ parentId, childId, attemptId, claimToken, ...outcome }) {
  let created = null;

  await runInTransaction(async (session) => {
    created = null;

    await assertChildIsActive({ parentId, childId }, { session });

    const snapshot = await activeLearningItemRepository.deleteClaimed(
      { parentId, childId, attemptId, claimToken },
      { session },
    );

    if (snapshot) {
      created = await learningAttemptRepository.create(buildAttemptFromSnapshot(snapshot, outcome), { session });
    }
  });

  return created;
}

// A replay, including a concurrent duplicate, returns the canonical attempt and writes nothing.
async function completeItem({ now = new Date(), ...request }) {
  const { parentId, childId, attemptId } = request;
  let created;

  try {
    created = await endClaimedItem({ ...request, endedAt: now });
  } catch (error) {
    if (!isDuplicateKey(error)) {
      throw error;
    }
  }

  if (created) {
    return { attempt: created, alreadyCompleted: false };
  }

  const existing = await learningAttemptRepository.findByAttemptId({ parentId, childId, attemptId });

  if (existing) {
    return { attempt: existing, alreadyCompleted: true };
  }

  const stillOpen = await activeLearningItemRepository.findByAttemptId({ parentId, childId, attemptId });

  throw new LearningItemError(stillOpen ? "conflict" : "not_found");
}

// Deleting the snapshot inside the archive transaction is what makes a racing
// completion conflict with it: the completion also deletes that snapshot, and
// reading the child alone would not collide with the archive's write.
async function archiveChildAndDiscardItems({ parentId, childId }) {
  let archivedChild = null;

  await runInTransaction(async (session) => {
    archivedChild = await parentRepository.archiveChild(parentId, childId, { session });

    if (archivedChild) {
      await activeLearningItemRepository.deleteAllForChild({ parentId, childId }, { session });
    }
  });

  return archivedChild;
}

export {
  startItem,
  claimItem,
  releaseItem,
  completeItem,
  archiveChildAndDiscardItems,
  LearningItemError,
  RESUME_WINDOW_MS,
  CLAIM_LEASE_MS,
};
